server.port: 8084
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/vcom?serverTimezone=UTC
    username: root
    password: Semangat1!1
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
  messages.basename: i18n/messages